### ISSUE TITLE
feat: 현좌석배치 api 개발

### ISSUE THREAD

**Issue by sdc05103** [Pda4thMiniProject4th/shitdown-be#11]
## ✨작성할 기능에 대한 설명을 적어주세요
```
`- method: GET
- url: seats/current`
```

<br><br>

## ✅ 해야 할 작업들을 작성해주세요
- [x] 현좌석배치 api 개발

<br><br>

## 🦋 연관된 이슈
- #12

**Comment by ShinHeeEul** [comment]
#12 와 같은 이슈인 것 같아 닫겠습니다 :0
